/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupervisorRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SupervisorOrganization;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.TechnicianWorkRequest;
import Business.WorkQueue.WaterLvlWorkRequest;
import Business.WorkQueue.WaterShortageWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.File;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Mayur
 */
public class ManageReportsWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageReportsWorkAreaJPanel
     */
     private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private Network network;
    private EcoSystem business;
    private DefaultTableModel model;
    public ManageReportsWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount,Organization organization, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = (SupervisorOrganization)organization;
        this.enterprise = enterprise;
        this.network = network;
        this.business = business;
        
        populateRequestComboBox();
        populateEmployeeComboBox();
        lblSupervisor.setText(userAccount.getEmployee().getName());
        ReportPathjTextField.setEnabled(false);
       
    }

      public void populateRequestComboBox(){
        RequestComboBox.removeAllItems();
        
        for (WorkRequest.RequestType type : WorkRequest.RequestType.values()) {
            RequestComboBox.addItem(type);
        }
    
    }
      
      public void populateEmployeeComboBox(){
          EmployeejComboBox.removeAllItems();
          
          for(UserAccount ua : business.getUserAccountDirectory().getUserAccountList()){
              EmployeejComboBox.addItem(ua);
          }
          for(Network network : business.getNetworkList())
          for(UserAccount ua : network.getUserAccountDirectory().getUserAccountList()){
              EmployeejComboBox.addItem(ua);
          }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RequestComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSupervisor = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        emailIDjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ReportPathjTextField = new javax.swing.JTextField();
        btnBrows = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        EmployeejComboBox = new javax.swing.JComboBox();
        empNamejLabel = new javax.swing.JLabel();

        RequestComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        RequestComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Requests");

        jLabel1.setText("Supervisor:");

        lblSupervisor.setText("jLabel2");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        btnPrint.setText("Print Report");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Status", "Result", "Request Date", "Resolve Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter Email ID to send Report:");

        jLabel4.setText("Report Path:");

        ReportPathjTextField.setInputVerifier(getInputVerifier());
        ReportPathjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportPathjTextFieldActionPerformed(evt);
            }
        });

        btnBrows.setText("Browse");
        btnBrows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowsActionPerformed(evt);
            }
        });

        jLabel5.setText("Employee:");

        EmployeejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        EmployeejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeejComboBoxActionPerformed(evt);
            }
        });

        empNamejLabel.setText("Emp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSupervisor))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backJButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPrint))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RequestComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ReportPathjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrows))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmployeejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(empNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(260, 260, 260)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSupervisor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RequestComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnPrint)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(EmployeejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empNamejLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ReportPathjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBrows)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void  populateRequestCreatedTable(WorkRequest.RequestType requestType){
    
       
        
          model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
        if( requestType != null){    
            Object[] row = new Object[6];
       
            if(request.getClass().getName().contains(requestType.getValue())){
            row[0] = request.getSender().getEmployee().getName();
            row[1] = request.getReceiver() == null ? "" : request.getReceiver().getEmployee().getName();
            row[2] = request.getStatus();
            
            if(requestType.getValue().equals("LabTestWorkRequest")){
            String result = ((LabTestWorkRequest) request).getTestResult();
            row[3] = result == null ? "Waiting" : result;
            }
            
            if(requestType.getValue().equals("WaterLvlWorkRequest")){
            String result = ((WaterLvlWorkRequest) request).getTestResult();
            row[3] = result == null ? "Waiting" : result;
             }
            
             if(requestType.getValue().equals("TechnicianWorkRequest")){
            String result = ((TechnicianWorkRequest) request).getTestResult();
            row[3] = result == null ? "Waiting" : result;
             }
              if(requestType.getValue().equals("WaterShortageWorkRequest")){
            String result = ((WaterShortageWorkRequest) request).getTestResult();
            row[3] = result == null ? "Waiting" : result;
             }
             
            row[4] = request.getRequestDate().toString();
            row[5] = request.getResolveDate()  == null ? "" : request.getResolveDate().toString() ;
            model.addRow(row);
            }
           
            
        }
        }
    }
    public  void SimpleReport() {
        JasperPrint jasperPrint = null;
        //TableModelData();
        try {
            JasperCompileManager.compileReportToFile("reports/SupervisorReports.jrxml");
            jasperPrint = JasperFillManager.fillReport("reports/SupervisorReports.jasper", new HashMap(),
                    new JRTableModelDataSource(model));
            JasperViewer jasperViewer = new JasperViewer(jasperPrint);
           // jasperViewer.setVisible(true);
            jasperViewer.viewReport(jasperPrint, false);
           
 
           
        } catch (JRException ex) {
            ex.printStackTrace();
        }
        
    }
    
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SupervisorWorkAreaJPanel dwjp = (SupervisorWorkAreaJPanel) component;

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

        SimpleReport();
    }//GEN-LAST:event_btnPrintActionPerformed

    private void RequestComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestComboBoxActionPerformed

        WorkRequest.RequestType requestType = (WorkRequest.RequestType) RequestComboBox.getSelectedItem();
        populateRequestCreatedTable(requestType);
    }//GEN-LAST:event_RequestComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        String recieverEmailId = emailIDjTextField.getText();
        String filePath = ReportPathjTextField.getText();
        String senderEmailId = userAccount.getEmailId();//"mayurs1690@gmail.com";
        if(organization.getUserAccountDirectory().validEmailId(recieverEmailId) && !filePath.isEmpty()){
            business.sendEmail(senderEmailId, recieverEmailId, filePath);
           JOptionPane.showMessageDialog(null,"Email sent succesfully...");
        }else{
            JOptionPane.showMessageDialog(null,"Please Enter the Valid Data");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBrowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowsActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String fileName = f.getAbsolutePath();
        ReportPathjTextField.setText(fileName);
    }//GEN-LAST:event_btnBrowsActionPerformed

    private void EmployeejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeejComboBoxActionPerformed
        UserAccount ua = (UserAccount) EmployeejComboBox.getSelectedItem();
        if(ua != null){
        empNamejLabel.setText(ua.getEmployee().getName());
        emailIDjTextField.setText(ua.getEmailId());
        }
    }//GEN-LAST:event_EmployeejComboBoxActionPerformed

    private void ReportPathjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportPathjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportPathjTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox EmployeejComboBox;
    private javax.swing.JTextField ReportPathjTextField;
    private javax.swing.JComboBox RequestComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnBrows;
    private javax.swing.JButton btnPrint;
    private javax.swing.JTextField emailIDjTextField;
    private javax.swing.JLabel empNamejLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSupervisor;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
