/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NetworkAdminRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WaterShortageWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.Validate;

/**
 *
 * @author Mayur
 */
public class NetworkAdminProcessWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NetworkAdminProcessWorkRequestJPanel
     */
    private JPanel userProcessContainer;
    private WaterShortageWorkRequest request;
    private Network network;
    private Enterprise enterprise;
    private UserAccount userAccount;
    
    private int waterAvail;
    private int waterProvide;
   
    
    public NetworkAdminProcessWorkRequestJPanel(JPanel userProcessContainer,UserAccount ua, WaterShortageWorkRequest request, Network network, Enterprise ent) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request; 
        this.network = network;
        this.enterprise = ent;
        this.userAccount = ua;
        
        lblnwAdmin.setText(ua.getEmployee().getName());
        waterAvail = network.getWaterAvail();
        waterProvide = request.getWaterShortage();
        
        lblWaterReq.setText(String.valueOf(waterProvide));
       popWaterLvl();
    }

     private void popWaterLvl(){
         waterAvialjLabel.setText(String.valueOf(waterAvail));
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        waterAvialjLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblnwAdmin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblWaterReq = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        waterProvidejTextField1 = new javax.swing.JTextField();

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Result");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Water Available:");

        waterAvialjLabel.setText("jLabel3");

        jLabel4.setText("Network Admin:");

        lblnwAdmin.setText("jLabel5");

        jLabel3.setText("Water Request:");

        lblWaterReq.setText("jLabel5");

        jLabel5.setText("Water Provide:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWaterReq)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(waterAvialjLabel)
                                .addGap(207, 207, 207)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblnwAdmin)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(submitJButton)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(waterProvidejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(resultJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(106, 106, 106))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblnwAdmin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(waterAvialjLabel))))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(resultJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblWaterReq)
                    .addComponent(jLabel5)
                    .addComponent(waterProvidejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(submitJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(121, 121, 121))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        if(Validate.isInteger(waterProvidejTextField1.getText())){
            waterProvide = Integer.parseInt(waterProvidejTextField1.getText());
       
        if(waterAvail > waterProvide){
    
            int wtrreq = enterprise.getWaterAvail() + waterProvide;
            if(wtrreq > enterprise.getWaterStorage()){
                 int waterextra = wtrreq - enterprise.getWaterStorage();
                 waterProvide = waterProvide - waterextra;
            }
            if(waterProvide < Integer.parseInt(waterProvidejTextField1.getText())){
                 JOptionPane.showMessageDialog(null, "Water Providing is more than Enterprise Sotrage Capacity");
                //int val = JOptionPane.showConfirmDialog(null, "Enter the value Under " +waterProvide);
                JOptionPane.showMessageDialog(null, "Enter the value Under " +waterProvide);
                return;
            }
            
            wtrreq = enterprise.getWaterAvail() + waterProvide;
            if(wtrreq == enterprise.getWaterAvail()){
                JOptionPane.showMessageDialog(null, "No water required");
                request.setWaterShortage(0);
                request.setStatus("Canceled");
                submitJButton.setText("Canceled");
                submitJButton.setEnabled(false);
            }else{
             waterAvail = waterAvail - waterProvide;
             network.setWaterAvail(waterAvail);
            enterprise.setWaterAvail(waterProvide + enterprise.getWaterAvail());
            JOptionPane.showMessageDialog(null, "released " + waterProvide +" Gallons of water");
            request.setWaterShortage(waterProvide);
            request.setStatus("Completed");
            submitJButton.setText("Completed");
            submitJButton.setEnabled(false);
              popWaterLvl();
            }
             request.setTestResult(resultJTextField.getText());
            
            request.setResolveDate(new Date());
        }
        }else{
            JOptionPane.showMessageDialog(null, "Enter Valid Water Provide");
        
        }
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageRequestWorkAreaJPanel dwjp = (ManageRequestWorkAreaJPanel) component;
        dwjp.populateTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblWaterReq;
    private javax.swing.JLabel lblnwAdmin;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel waterAvialjLabel;
    private javax.swing.JTextField waterProvidejTextField1;
    // End of variables declaration//GEN-END:variables
}
